### ISSUE TITLE
Enable editation of the input

### ISSUE THREAD

**Issue by hank-milliken** [minimalist-freedom-apps/price-converter#34]
- [x] When you tab selected number the input second time, it shall be possible to edit the number (currently it persist the selection of the whole input and it is not possible to perform the edit)

**Comment by hank-milliken** [comment]
If I see it correctly it is achvied by setting `.setSelectAllOnFocus(true);` on the `EditText`

**Comment by hafizsaadiftikhar** [comment]
There is no EditText in Jetpack Compose. Please don't consider simple kotlin with xml. I tried the same behavior in Jetpack Compose but the problem is the same that I mentioned earlier

**Comment by hank-milliken** [comment]
Hmm Understood. I have played around with the code. Can you please share the code what you have done for the provided APK?

**Comment by hank-milliken** [comment]
I have played a little bit with the code I this is working for me

https://github.com/Minimalistic-Apps/price-converter/pull/42/commits/7735cbdcbcb6531bf521ac2d7bea4d3c674f3d92

(I have commented out the BTC formatting logic, to make it easier to demonstrate the functionality.)

**Comment by hank-milliken** [comment]
An after I have implemented it I have found this solution that seems to work: https://stackoverflow.com/a/72504219

**Comment by hank-milliken** [comment]
I have tested it here, and it seems it works: https://github.com/Minimalistic-Apps/price-converter/pull/42/commits/01ae2e5bb23872f9c4a0cd5211716273adddf21e

**Comment by hafizsaadiftikhar** [comment]
How do you want to receive the code for this apk, Please let me know?

And please join Jira. It would be easy for us to communicate there on each ticket

**Comment by hank-milliken** [comment]
@hafizsaadiftikhar yes I am in jira, I have mentioned you in the relevant issue
