### ISSUE TITLE
Re-implement more currencies

### ISSUE THREAD

**Issue by Nikoichu** [minimalist-freedom-apps/price-converter#60]
The recent update removed some currencies, including BGN, that I used on the older version, which is why I downgraded back to it.

**Comment by hank-milliken** [comment]
Hi, thank you very much for you feedback. Sorry for this regression. This issue is covered by #41 and it is because the only currently working provider Coingecko is missing some currencies.

The desired state is to have all 3 providers back and do an average of their rates.

I will make this priority and I hopefully fix it soon.

**Comment by hank-milliken** [comment]
The PR #62 solves your Issue + much more ;)

I need to add one more provider before I merge it. But if you are able to build and run the code, I will be happy if you can test it. ;)


![signal-2022-08-22-031314](https://user-images.githubusercontent.com/89867413/185820545-ff8f0fd7-7691-4e60-a0f8-28aaf0962195.png)

![signal-2022-08-22-031305](https://user-images.githubusercontent.com/89867413/185820552-369f49d3-c99c-41e4-9a90-4f6782a43ce3.png)

**Comment by BloodRaven0** [comment]
@hank-milliken That's awesome!
Sadly I'm not tech-savvy enough to build it on my own, so I'll just wait for the update on F-Droid.

**Comment by hank-milliken** [comment]
@BloodRaven0 Merged, you can download build directly from Github here https://github.com/Minimalistic-Apps/price-converter/releases/tag/2.5.0

:exclamation: But make sure you uninstall it before you download it from F-Droid. Github build is signed by my key, the build from F-Droid is signed by them and it is not possible to upgrade apps with mismatching keys.
