### ISSUE TITLE
Add lightning address to app for tipping

### ISSUE THREAD

**Issue by kirkawolff** [minimalist-freedom-apps/price-converter#64]
Right now the only option to donate is to pay $2 for the app via a lnbits link. This 10ksat mininum prevents tipping and if you're going to put a big button at the top for lightning payments you might as well permit micropayments. An alternative could be to add a second tipping button that has your lightning address in it.

**Comment by hank-milliken** [comment]
Hi, thank you very much for donations, do you mean to use

**Comment by kirkawolff** [comment]
A lightning address is like an email address but you can put it into a lightning wallet. The wallet knows to look up a LNURLp URI which in turn requests an invoice from your lightning node and the wallet uses this to send funds to.

There are three steps to setting it up for your own domain:
1) decide what your lightning address should be, such as donate@lnpriceconverter.com where the domain name points to a web server you control
2) Set up an LNURLp instance somewhere, either self-hosted or on https://legend.lnbits.com/
3) Add a file to your /.well-known/ directory on your webserver that points to your LNURLp instance

An alternative is to use WOS, Alby, or Stacker.news ln addresses (price-converter@getalby.com or price-converter@stacker.news) and just post that somewhere to be copied into a wallet

Here are a few websites to look into it further:
* https://stacker.news/items/65872
* https://stacker.news/items/3191
* https://thebitcoinmanual.com/articles/lightning-email-address/

**Comment by TimothyShimmin** [comment]
Prefer this to donation bug fix
