### ISSUE TITLE
Entering digits into sats field shifts cursor 

### ISSUE THREAD

**Issue by kirkawolff** [minimalist-freedom-apps/price-converter#66]
As you're entering numbers, all the other fields update after each digit entry. After entering 4 digits, the thousands separator insertion appears to shift the cursor to the left causing incorrect data entry

**Comment by hank-milliken** [comment]
Can you please provide screenshots or better video? Or some better steps to reproduce. 

This is not happening to me. When I type in Sats mode I just always have cursor at the end of the input's string even the `,` was added.

**Comment by kirkawolff** [comment]
It appears this problem was fixed. I'm not able to reproduce it on the most recent version.
