### ISSUE TITLE
Donations not working

### ISSUE THREAD

**Issue by apemithrandir** [minimalist-freedom-apps/price-converter#71]
I downloaded the app using F-Droid. When I click the donate button the next screen that pops up has the Thank You message but the Donate button is greyed out with a HTTP 500 Internal Server Error.

![donate](https://github.com/Minimalistic-Apps/price-converter/assets/99969638/5b1873bf-7d02-4fb2-893a-da5aa36937b9)

**Comment by BarefootJohn** [comment]
I am getting (almost) the same error. I got a HTTP 410 instead of 500.

**Comment by BonHodl** [comment]
Same errors for me. I've wanted to donate some sats for a long time but never can.

**Comment by TimothyShimmin** [comment]
Same problem

**Comment by hank-milliken** [comment]
Hi, thanks for reporting. I got a bit busy with my life and forgot to maintain the server. 

Lesson learned. I try to change it and add just LN address instead (or something).
