### ISSUE TITLE
Error 403 is showing as i try to refresh app

### ISSUE THREAD

**Issue by p01nt3r80** [minimalist-freedom-apps/price-converter#76]
As per title .. I got 403 error ... It happening from a couple of day ago

**Comment by emtreulapollaguera** [comment]
I have been digging a bit and it looks an error with  one of the API endpoint URL:

https://bitpay.com/rates : The endpoint is down. It appears to be experiencing technical difficulties.

https://blockchain.info/ticker : The endpoint is up and responding with a 200 status code.
 https://api.coingecko.com/api/v3/exchange_rates : The endpoint is up and responding with a 200 status code.

I hope the maintainers can look and update it soon. The app is simple but very useful and people like me that have donated deserves at least an answer from the devs.

**Comment by hank-milliken** [comment]
Hello, thank you for the report. For me the app is working (and always was). The only issue that is known to me are VPNs. Sometimes some of the API that is used gets blocked from VPN. The change of the VPN server helps most of the time (I tested Mullvad and iVPN).

What is a but unfortunate is, that if **any** of the APIs return error, the app wont update the price from the rest. This is a bug, but I don't feel the urge to fix it as I have very little time anyway.
